import React from 'react';
import './Info.css';
import wind1 from '../../assets/images/wind1.jpg'
import wind2 from '../../assets/images/wind2.jpg'
import{BrowserRouter as Router,Link} from 'react-router-dom';
import Route from 'react-router-dom/Route';
function windInfo() {
    return (
        <div id = "windbg">
        
        <h3 id="head1"><i>WIND ENERGY</i></h3>
        <div id="wind">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src={wind1} alt="First slide"/>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src={wind2} alt="Second slide"/>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>       

<div id="head2">

   
  <p >Wind power is one of the fastest-growing renewable energy technologies. Usage is on the rise worldwide, in part because costs are falling. Global installed wind-generation capacity onshore and offshore has increased by a factor of almost 75 in the past two decades, jumping from 7.5 gigawatts (GW) in 1997 to some 564 GW by 2018, according to IRENA's latest data. Production of wind electricity doubled between 2009 and 2013, and in 2016 wind energy accounted for 16% of the electricity generated by renewables. Many parts of the world have strong wind speeds, but the best locations for generating wind power are sometimes remote ones. Offshore wind power offers tremendous potential.Wind turbines first emerged more than a century ago. Following the invention of the electric generator in the 1830s, engineers started attempting to harness wind energy to produce electricity. Wind power generation took place in the United Kingdom and the United States in 1887 and 1888, but modern wind power is considered to have been first developed in Denmark, where horizontal-axis wind turbines were built in 1891 and a 22.8-metre wind turbine began operation in 1897.Wind is used to produce electricity using the kinetic energy created by air in motion. This is transformed into electrical energy using wind turbines or wind energy conversion systems. Wind first hits a turbine’s blades, causing them to rotate and turn the turbine connected to them. That changes the kinetic energy to rotational energy, by moving a shaft which is connected to a generator, and thereby producing electrical energy through electromagnetism.The amount of power that can be harvested from wind depends on the size of the turbine and the length of its blades. The output is proportional to the dimensions of the rotor and to the cube of the wind speed. Theoretically, when wind speed doubles, wind power potential increases by a factor of eight.Wind-turbine capacity has increased over time. In 1985, typical turbines had a rated capacity of 0.05 megawatts (MW) and a rotor diameter of 15 metres. Today’s new wind power projects have turbine capacities of about 2 MW onshore and 3–5 MW offshore.Commercially available wind turbines have reached 8 MW capacity, with rotor diameters of up to 164 metres. The average capacity of wind turbines increased from 1.6 MW in 2009 to 2 MW in 2014.</p>
   
 
 </div>
        
        <div><h1>                                                                 </h1></div>
        
        </div>
        )};

        export default windInfo;